export const MOBILE_OPEN = 'MOBILE_OPEN'
export const MOBILE_CLOSE = 'MOBILE_CLOSE'
export const GET_PARTS_BEGIN = "GET_PARTS_BEGIN"
export const GET_PARTS_SUCCESS = "GET_PARTS_SUCCESS"
export const GET_PARTS_ERROR = "GET_PARTS_ERROR"

export const LOAD_PARTS = "LOAD_PARTS"
export const UPDATE_SORT = "UPDATE_SORT"
export const SORT_PARTS = "SORT_PARTS"
export const UPDATE_FILTERS = "UPDATE_FILTERS"
export const FILTER_PARTS = "FILTER_PARTS"
export const CLEAR_FILTERS = "CLEAR_FILTERs"